apiVersion: v1
kind: Service
metadata:
  name: prometheus-demo-service
  namespace: monitoring
spec:
  selector:
    app: prometheus-demo-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
